= Historias de Usuario

== Introduccion

Este documento presentara el detalle de todas las historias de usuario para la construccion de un bot de telegram para restaurantes.

La funcionalidad proyectada para el bot sera: 

Para los clientes: 

. Los clientes pueden ver el menu
. El cliente debe poder realizar pedidos
. Los clientes pueden solicitar información sobre el restaurante

Para el personal de Restaurant:

. El personal podra aceptar o rechazar pedidos 
. El encargado debe poder modificar el menu que se muestra 
. El personal podra realizar el cobro por medio de un codigo QR 
. El personal de Restaurant podra configurar el menu de opciones que se muestran

== Historias de Usuario

== 001-Notificacion de promociones

*Autor*: Kevin Lecoña Marca

*Fecha*: 08/03/2022

*Propiedad*: MEDIA

## Descripcion

El `Dueño de restaurante` por medio del Bot crea un mensaje de promocion y añadiendo una imagen publicitaria, de no tener ambos no podra crear la promocion. Una vez enviada la promocion deberia llegar a todos los `clientes`, el cliente tendra la opcion de realizar el pedido de la promocion:

La promocion pasara por los siguientes

* *Realizar pedido*: El pedido sera enviado al restaurante
* *Rechazar*: Rechazar pedido

Diagrama de estados para la `PROMOCION` sera:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> AGREGAR PROMOCION
AGREGAR PROMOCION -> NO_VALIDA
NO_VALIDA --> [*]
[*] --> AGREGAR PROMOCION
AGREGAR PROMOCION -> VALIDA
AGRADO --> [*]
@enduml
....

#### Escenarios

1. Promocion enviada
2. Promocion no enviada

#### Caso de prueba

*100.1.1 Promocion no enviada* 

Descripción: La promocion no a sido enviada correctamente ya se por la falta de una descripcion o una imagen de dicha pormocion.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Crear Promocion: Ninguno
    - Resultado a esperar: El BOT retorna un mensaje de "introducir descripcion e imagen"

== 002 - Recepcion de Pedidos 

*Autor:* Ariel Monroy

*Fecha:* 8/3/2022

*Prioridad:* ALTA

### Descripcion 

El `Cliente` debe seleccionar los platos que el desee junto con las cantidades de estos por medio del menu del bot, despues debe añadir la ubicación para la entrega y finalmente enviar el `Pedido`. En el restaurant el `Encargado de Pedidos` debe verificar si el restaurant puede cumplir con el `Pedido` para que este sea aceptado o rechazado. En caso de que el `Pedido` sea aceptado se debe dar una hora estimada de llegada. Por otra parte si el `Pedido` fue rechazado el restaurant debe dar un comentario del porque. Además el `Cliente` puede cancelar el pedido antes de que este sea aceptado. 

El Pedido pasará por los siguientes estados: 

* *Enviado:* El pedido fue enviado para la revision por el `Encargado de pedidos` 
* *Aceptado:* El pedido fue aceptado por el restaurante y procedera a ser preparado para el envio. 
* *Rechazado:* El Pedido fue rechazado por el Restaurante.
* *Cancelado:* El pedido fue Cancelado por el `Cliente` antes de ser aceptado por el restaurant 

Diagrama de estados para el `Pedido`: 
[plantuml, format="png, id="estados-pedido"]
....
@startuml
[*] --> ENVIADO 
ENVIADO --> ACEPTADO
ENVIADO --> RECHAZADO
ENVIADO --> CANCELADO
ACEPTADO --> [*]
RECHAZADO --> [*]
CANCELADO--> [*]
@enduml
....

#### Escenario
. El pedido se rechaza por no poder cumplirlo en su totalidad
. El pedido es aceptado
. El pedido es cancelado
. El pedido se envía

#### Casos de Prueba

*002.1.1* 

Descripción: El pedido fue enviado pero el restaurante no puede cumplir con lo requerido por lo que rechaza el pedido.

Pasos:
    
    .  Ingresar al bot y enviar el comando /start  y seleccionar los platos y la dirección para enviar el pedido. 

    - Datos: Platos seleccionados y Dirección 

   - Resultado: El bot retorna un mensaje de la confirmación de la recepción. 

    .  Ingresar al bot y buscar la sección de pedidos recibidos y rechaza el pedido.

    - Datos: Ninguno

    - Resultado: El bot retorna un mensaje del plato que no puede ser preparado. 

*002.1.2* 

Descripción: El pedido fue enviado y aceptado por lo que se procede preparar y enviar.

Pasos:

    .  Ingresar al bot y enviar el comando /start  y seleccionar los platos y la dirección para enviar el pedido. 

    - Datos: Platos seleccionados y Dirección 

   - Resultado: El bot retorna un mensaje de la confirmación de la recepción. 


    . Ingresar al bot y buscar la sección de pedidos recibidos y aceptar el pedido.

    - Datos: Ninguno

    - Resultado: El bot retorna un mensaje al cliente con una hora estimada de la llegada del pedido


*002.1.3*

Descripción: El pedido fue enviado, pero el cliente decide cancelarlo

Pasos:

    
    .  Ingresar al bot y enviar el comando /start  y seleccionar los platos y la dirección para enviar el pedido. 
    
    - Datos: Platos seleccionados y Dirección 
   El bot retorna un mensaje de la confirmación de la recepción. 

    . Ingresar al pedido en curso dentro del bot y presionar el boton de cancelar

    - Datos: Ninguno

    - Resultado: El bot retorna un mensaje con una hora estimada de la llegada del pedido

*002.1.4*

Descripción: El pedido fue enviado y espera por la revisión.

Pasos:

    .  Ingresar al bot y enviar el comando /start  y seleccionar los platos y la dirección para enviar el pedido. 
    - Datos: Platos seleccionados y Dirección 
    - Resultado: El bot retorna un mensaje de la confirmación de la recepción. 

== 003 - Metodo de pago

*Autor*: Ignacio Carvajal

*Fecha*: 08/03/2022

*Prioridad*: ALTA

### Descripción

Un `Cliente` debe solicitar el método de pago por medio del bot, para esto debe enviar los platos que desea solicitar. Una vez enviada la solicitud de los platos deseados un `Encargado del Restaurante` procederá a mandar un QR de cobro en caso de ser aceptado el pedido, en caso contrario no se le mandará el QR y se le mandará un mensaje de los platos que no se pueden mandar 

La solicitud pasará por los siguientes estados:

* *SOLICITADO*: Cuando el cliente envía su solicitud al BOT y el BOT no la rechaza.
* *APROBADO*: Solicitud aprobada por el encargado del Restaurante
* *RECHAZADO*: Solicitud rechazada por el encargado del Restaurante
* *PAGADO*: El cliente paga lo pedido
* *CANCELADO*: El cliente canceló una solicitud APROBADA mientra no haya enviado el pago
El diagrama de estados para la `SOLICITUD` será:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> SOLICITADO
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
APROBADO -> PAGADO
APROBADO -> CANCELADO
PAGADO --> [*]
CANCELADO --> [*]
@enduml
....

#### Escenarios
1. El encargado del restaurante aprueba y manda el QR
2. El encargado del restaurante rechaza y no manda el QR
3. El cliente paga el pedido
4. El cliente no paga el pedido
5. El cliente cancela el pedido

#### Casos de Prueba

*003.1.1 Encargado manda el QR*

Descripción: El encargado verifica la disponibilidad de los pedidos y una vez ve que todo lo que pidió esta disponible manda el QR

Pasos:

1. El cliente envia el pedido
    - Datos: pedidos
    - Resultado: El BOT retorna un mensaje. "*Manda QR*"

*003.1.2 Encargado manda el QR*

Descripción: El encargado verifica la disponibilidad del pedido y una vez ve que no hay disponibilidad de algunos pedidos rechaza el pedido y mandan mensaje de los pedidos no disponibles

Pasos:

1. El cliente envia el pedido
    - Datos: platos
    - Resultado: El BOT retorna un mensaje. "Los siguientes pedidos no estan disponibles: ...."

*003.1.3 El cliente paga el pedido*

Descripción: El encargado manda el QR y el cliente manda el comprobante de pago

Pasos:

1. El encargado envía el QR
    - Datos: QR
    - cliente: El cliente retorna un mensaje. "*Comprobante*"

*003.1.4 El cliente no paga el pedido*

Descripción: El encargado manda el QR y el cliente no manda el comprobante de pago y luego de un 10 minutos de no recibir el comprobante se cancela el pedido

Pasos:

1. El encargado envía el QR
    - Datos: QR
    - cliente: El cliente no retorna un mensaje.
    -Bot: El pedido fue cancelado

*003.1.5 El cliente cancela el pedido*

Descripción: El encargado manda el QR y el cliente cancela el pedido

Pasos:

1. El encargado envía el QR
    - Datos: QR
    - cliente: El cliente retorna un mensaje. "Cancelo el pedido"
    -Bot: El pedido fue cancelado