= Historias de Usuario

== Introducción

Este documento presentará el detalle de todas las historias de usuario para la construccion de un bot de telegram para restaurantes.

La funcionalidad proyectada para el bot será:

Para los clientes: 

. El `Cliente` puede ver el menu
. El `Cliente` debe poder realizar pedidos
. El `Cliente` puede solicitar información sobre el restaurante

Para el personal de Restaurant:

. El `Encargado` podrá aceptar o rechazar pedidos
. El `Encargado` debe poder modificar el menu que se muestra
. El `Encargado` podrá realizar el cobro por medio de un código QR
. El `Encargado` de Restaurant podrá configurar el menu de opciones que se muestran

== Historias de Usuario

== 001-Notificacion de promociones

*Autor*: Kevin Lecoña Marca

*Fecha*: 08/03/2022

*Propiedad*: MEDIA

## Descripcion

El `Encargado` por medio del Bot puede crear un mensaje de promocion y enviar a sus clientes, para realizar el mensaje de promocion se requerira de un titulo, descripcion e imagen, Asi mismo el `Encargado` podra ver un listado de promociones que se crearon.


La promocion pasara por los siguientes

* *Realizar pedido*: El pedido sera enviado al restaurante
* *Rechazar*: Rechazar pedido

Diagrama de secuencia para crear y enviar una `PROMOCION` sera:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

actor encargado
participant bot
actor clientes
encargado->bot: iniciar bot (/start)
bot->encargado: Menu de opciones(Lista de pedidos/promociones/cambiar el menu)
encargado->bot: promociones
bot->encargado: (crear promocion/ listado de promociones)
encargado->bot: crear promocion
bot -> encargado: agregar Titulo, descripcion e imagen
encargado -> bot: llenar datos
bot->encargado: Promocion enviada a los clientes
bot->clientes: enviar promocion
@enduml
....
Diagrama de secuencia para ver el listado de promociones `PROMOCION` sera:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

actor encargado
participant bot
encargado->bot: iniciar bot (/start)
bot->encargado: Menu de opciones(Lista de pedidos/promociones/cambiar el menu)
encargado->bot: promociones
bot->encargado: (crear promocion/ listado de promociones)
encargado->bot: listado de promociones
bot -> encargado: Mostrar todas las promociones creadas
@enduml
....

#### Escenarios

1. Promocion enviada
2. Promocion no enviada
3. Falta de descripcion
4. Falta de imagen
5. Falta de Titulo



== 002 - Recepción de Pedidos

*Autor:* Ariel Monroy

*Fecha:* 8/3/2022

*Prioridad:* ALTA

### Descripción

El `Cliente` debe seleccionar los platos que él desee junto con las cantidades de estos por medio del menú del bot, después debe añadir la ubicación para la entrega y finalmente enviar el `Pedido` En el restaurante el `Encargado` debe verificar si el restaurante puede cumplir con el `Pedido` para que este sea aceptado o rechazado. En caso de que el `Pedido` sea aceptado  el pedido un `Encargado` procederá a mandar un QR y se dará una hora estimada de llegada. Por otra parte si el `Pedido` fue rechazado el restaurante debe dar un comentario de los productos que no se puedan enviar.
Una vez que el `Cliente` realice el pago este debe mandar el comprobante al bot para que el `Pedido` sea preparado,el comprobante será verificado por el `Encargado`, en caso de que no se realice el pago antes de 10 minutos el bot cancelará automáticamente el `Pedido`.

El Pedido pasará por los siguientes estados:

* *ENVIADO:* Cuando el cliente envía su `Pedido` al BOT para ser revisado por el `Encargado`.
* *APROBADO*: Solicitud aprobada por el `Encargado` del Restaurante
* *RECHAZADO*: Solicitud rechazada por el `Encargado` del Restaurante
* *PAGADO*: El `Cliente` realiza el pago
* *CANCELADO*: El `Cliente` cancela una solicitud aprobada si no realiza el pago dentro del límite de tiempo, o si decide cancelarla antes de sea aprobada.

El diagrama de estados para  el `PEDIDO` será:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> ENVIADO
ENVIADO --> APROBADO
ENVIADO --> RECHAZADO
ENVIADO ---> CANCELADO
RECHAZADO ---> [*]
APROBADO --> PAGADO
APROBADO -> CANCELADO
PAGADO --> [*]
CANCELADO --> [*]
@enduml
....



#### Escenario
. El pedido se envía para ser revisado por el `Encargado`.
. El `Encargado` del restaurante aprueba y manda el QR
. El `Encargado` del restaurante rechaza el pedido
. El `Cliente` el pago del pedido
. El pedido se cancela por haber excedido el tiempo de pago
. El `Cliente` cancela el pedido antes de ser aprobado
. El `Cliente` cancela el pedido antes de realizar el pago



#### Casos de Prueba

*002.1.1* El pedido se envía para ser revisado por el `Encargado`.

Descripción: El pedido fue enviado y espera por la revisión del `Encargado`.

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.


*002.1.2*  El `Encargado` del restaurante aprueba y manda el QR

Descripción: El pedido fue enviado y aprobado por el ´Encargado´

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, este contiene la hora   de estimada de llegada, el total del pedido incluyendo delivery y un QR para el pago .

*002.1.3* El `Encargado` del restaurante rechaza el pedido

Descripción: El pedido fue enviado y rechazado por el `Encargado`

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` rechaza el pedido
- Datos: Ninguno
- Resultado: El bot retorna un mensaje  "Los siguientes productos no están disponibles: ...."

*002.1.4*  El `Cliente` realiza el pago del pedido

Descripción: El pedido fue enviado y aprobado por el ´Encargado´, después este responde con un código QR para que se realice el pago del ´Pedido´.

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, el total del pedido incluyendo delivery y un QR para el pago.

. El `Cliente` realiza el pago mediante el código QR y envía el comprobante de la transferencia para su revisión.
- Datos: Comprobante de pago
- Resultado: El bot retorna un mensaje de confirmación, este contiene la hora   de     estimada de llegada .






*002.1.5* El pedido se cancela por haber excedido el tiempo de pago

Descripción: El pedido fue enviado, pero el `Cliente` decide cancelarlo

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, este contiene la hora   de estimada de llegada, el total del pedido incluyendo delivery y un QR para el pago .

. El ´Bot´ manda notificaciones cada 5 minutos durante 11 minutos.
- Datos: Ninguno
- Resultado: El bot retorna mensajes de “Le quedan … minutos para mandar el comprobante de pago”.

. El `Cliente` no manda el comprobante .
- Datos: Ninguno
- Resultado: El bot retorna un mensaje “El pedido fue cancelado”.

*002.1.6*  El `Cliente` cancela el pedido antes de ser aprobado

Descripción: El pedido fue enviado pero el `Cliente`  decide cancelarlo antes de que el `Encargado` lo apruebe.

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Cliente` ingresa el comando para cancelar su pedido en curso
- Datos: Ninguno
- Resultado: El bot retorna un mensaje de confirmación de la cancelación.

*002.1.7* El `Cliente` cancela el pedido antes de realizar el pago

Descripción: El pedido fue enviado, pero el `Cliente` decide cancelarlo

Pasos:
.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, este contiene la hora   de estimada de llegada, el total del pedido incluyendo delivery y un QR para el pago .

. El `Cliente` cancela el pedido.
- Datos: Ninguno
- Resultado: El bot retorna un mensaje “El pedido fue cancelado”.

