= Historias de Usuario

== Introducción

Este documento presentará el detalle de todas las historias de usuario para la construccion de un bot de telegram para restaurantes.

La funcionalidad proyectada para el bot será:

Para los clientes: 

. El `Cliente` puede ver el menu
. El `Cliente` debe poder realizar pedidos
. El `Cliente` puede solicitar información sobre el restaurante

Para el personal de Restaurant:

. El `Encargado` podrá aceptar o rechazar pedidos
. El `Encargado` debe poder modificar el menu que se muestra
. El `Encargado` podrá realizar el cobro por medio de un código QR
. El `Encargado` de Restaurant podrá configurar el menu de opciones que se muestran

== Historias de Usuario

== 001-Notificación de promociones

*Autor*: Kevin Lecoña Marca

*Fecha*: 08/03/2022

*Propiedad*: MEDIA

== Descripción

El `Encargado` por medio del Bot puede crear un mensaje de promoción y enviar a sus clientes, para realizar el mensaje de promoción se requerirá de un título, descripción e imagen, Asi mismo el `Encargado` podrá ver un listado de promociones que se crearon.


La promoción pasará por los siguientes estados:

* *Crear promocion*: el proceso de creacion de la promocion
* *Lista de promociones*: Verificacion que la promocion a sido enviada

Diagrama de secuencia para crear y enviar una `PROMOCION` sera:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

actor encargado
participant bot
actor clientes
encargado->bot: iniciar bot (/start)
bot->encargado: Menu de opciones(Lista de pedidos/promociones/cambiar el menu)
encargado->bot: promociones
bot->encargado: (crear promocion/ listado de promociones)
encargado->bot: crear promocion
bot -> encargado: agregar Titulo, descripcion e imagen
encargado -> bot: llenar datos
bot->encargado: Promocion enviada a los clientes
bot->clientes: enviar promocion
@enduml
....

Diagrama de secuencia para ver el listado de promociones `PROMOCION` sera:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

actor encargado
participant bot
encargado->bot: iniciar bot (/start)
bot->encargado: Menu de opciones(Lista de pedidos/promociones/cambiar el menu)
encargado->bot: promociones
bot->encargado: (crear promocion/ listado de promociones)
encargado->bot: listado de promociones
bot -> encargado: Mostrar todas las promociones creadas
@enduml
....

=== Escenarios

1. Promoción enviada
2. Validacion de datos


=== Caso de prueba

*001.1.1 Validacion de datos*

Descripcion: La promocion no a sido enviada correctamente ya sea por problemas de conexion o cualquier otro problema

Pasos:

1. Ingresar al Bot enviando el mensaje /start
Resultado: Selecione una opcion
- Lista de pedidos
- Promociones
- Cambiar el menu
2. Ingresa a la opcion de promocion
Resultado: Selecione una opcion
- Crear promocion
- Lista de promociones
3. El `ENCARGADO` crear una promocion /crear
- datos /crear
- resultado ingrese Titulo
4. El `ENCARGADO` coloca espacios en blanco
- datos /un espacio en blanco
- resultado /El Bot le pide al encagado el titulo nuevamente
5. El `ENCARGADO` coloca el titulo para la promocion
- datos /Titulo
- resultado /Ingrese descripcion
6. El `ENCARGADO` coloca un espacion en blanco
- datos /espacio en blanco
- resultado /El Bot le pide al encargado la descripcion nuevamente
7. El `ENCARGADO` coloca una descripcion
- datos /descripcion
- resultado /selecione una imagen

*001.1.2 Promocion enviada*

Descripcion: La promocion se envio correctamente a todos los clientes

Pasos:

1. Ingresar al Bot enviando el mensaje /start
Resultado: Selecione una opcion
- Lista de pedidos
- Promociones
- Cambiar el menu
2. Ingresa a la opcion de menu
Resultado: Selecione una opcion
- Crear promocion
- Lista de promociones
3. El `ENCARGADO` crear una promocion /crear
- datos /crear
- resultado ingrese Titulo
4. El `ENCARGADO` coloca el titulo para la promocion
- datos /Titulo
- resultado /Ingrese descripcion
5. El `ENCARGADO` coloca una descripcion
- datos /descripcion
- resultado /selecione una imagen
6. El `ENCARGADO` coloca una imagen para la promocion
- datos /imagen
- resultado /promocion enviada

== 002 - Adición de productos del menú al pedido

*Autor:* Ignacio Carvajal

*Fecha:* 10/3/2022

*Prioridad:* ALTA

### Descripción

El `Cliente` debe entrar menú desde la lista de opciones del bot, para seleccionar qué categoría de producto desea pedir, para añadir un productos a la lista del pedido el `Cliente` deberá clickear sobre el nombre del producto que desea pedir y el bot mandará un mensaje preguntando la cantidad que desea pedir, el `cliente` podrá retractarse de la orden presionando en cancelar antes de poner la cantidad que desee pedir, una vez enviado la cantidad el bot mandará un mensaje preguntando si desea hacer algún otro pedido en esta categoría o desea hacer algún pedido en otra categoría o desea ir a los pedidos, en caso de ir a los pedidos el `cliente` podrá ver la lista de los productos seleccionados, las cantidades, costo total y cuatro opciones: añadir producto, eliminar producto, editar producto y enviar pedido, añadir producto lo enviará al menú, eliminar producto te pedirá que ingreses el número del pedido que deseas eliminar, editar producto te pedirá que ingreses el número del pedido que deseas editar y enviar pedido mandara la lista al `Encargado`
[plantuml, format="png", id="secuencia-adición"]
....
@startuml
actor Cliente
participant Bot
database BDD
Cliente -> Bot: Solicitar el Menú
Bot -> BDD: Realiza consulta del Menú
Bot <- BDD: Envía datos sobre el Menú
Cliente <- Bot: Muestra el Menú
Cliente -> Bot: Selecciona producto
Bot -> Cliente: "Ingrese Cantidad"
Cliente -> Bot: Ingresa Cantidad
Bot -> BDD: Guarda en la lista
@enduml
....

[plantuml, format="png", id="secuencia-edición"]
....
@startuml
actor Cliente
participant Bot
database BDD
Cliente -> Bot: Solicita pedido actual
Bot -> BDD: Solicita pedido
Bot <- BDD: Envia datos del pedido
Cliente <- Bot: Muestra datos del pedido
Cliente -> Bot: Editar pedido
Bot -> Cliente: "Ingrese nueva cantidad"
Cliente -> Bot: Ingresa Cantidad
Bot -> BDD: Guarda la lista
@enduml
....

[plantuml, format="png", id="secuencia-eliminación"]
....
@startuml
actor Cliente
participant Bot
database BDD
Cliente -> Bot: Solicita pedido actual
Bot -> BDD: Solicita pedido
Bot <- BDD: Envia datos del pedido
Cliente <- Bot: Muestra datos del pedido
Cliente -> Bot: Eliminar producto del pedido
Bot -> Cliente: "Ingrese producto"
Cliente -> Bot: Ingresa producto
Bot -> BDD: Guarda la lista
@enduml
....

#### Escenario
. El cliente agrega productos a su lista de pedido
. El cliente edita productos de su lista de pedido
. El cliente elimina productos de su lista de pedido
. El cliente ingresa una cantidad inválida

#### Casos de Prueba

*002.1.1*  El cliente agrega productos a su lista de pedido

Descripción: El cliente entra al menú selecciona la categoría y empieza a adicionar productos junto con la cantidad que desea del producto.

Pasos:

.  El ´Cliente´ ingresa al bot, envía el comando /start y  selecciona la opción menú
- Datos: Ninguno
- Resultado: El bot retorna un mensaje “A qué categoría desea ingresar”

. El ́Cliente ́ ingresa a alguna categoría.
- Datos: categoría
- Resultado: El bot retorna un mensaje “Lista de productos:”.

. El `cliente` Selecciona el producto que desea.
- Datos: producto
- Resultado: El bot retorna un mensaje “Cantidad que desea pedir:”.

. El `cliente` Manda una cantidad
- Datos: cantidad
- Resultado: El bot retorna un mensaje “Se agregó exitosamente”.

*002.1.2*  . El cliente edita productos de su lista de pedido

Descripción: El Cliente ya adiciono platos a su pedido pero quiere editar las cantidades de estos

Pasos:

.  El ´Cliente´ ingresa al bot, y entra la opción mi pedido y  selecciona los platos para el pedido
- Datos: Ninguno
- Resultado: El bot retorna la lista de todos los productos en su lista

. El ´Cliente´ selecciona el producto que desea editar
- Datos: Producto a editar
- Resultado: El bot envía un mensaje pidiendo la cantidad nueva

. El ´Cliente´ ingresa la nueva cantidad
- Datos: Cantidad
- Resultado: El bot devuelve un mensaje de confirmación de la edición

*002.1.3*  . El cliente elimina productos de su lista de pedido

Descripción: El Cliente ya adiciono platos a su pedido pero quiere eliminar cierto producto

Pasos:

.  El ´Cliente´ ingresa al bot, y entra la opción mi pedido y  selecciona los platos para el pedido
- Datos: Ninguno
- Resultado: El bot retorna la lista de todos los productos en su lista

. El ´Cliente´ selecciona el producto que desea eliminar
- Datos: Producto a eliminar
- Resultado: El bot envía un mensaje pidiendo una confirmación

. El ´Cliente´ confirma la eliminación
- Datos: Ninguno
- Resultado: El bot devuelve un mensaje de confirmación de la eliminación

*002.1.4*  . El cliente ingresa una cantidad inválida

Descripción: El cliente entra al menú selecciona la categoría y empieza a adicionar productos pero la cantidad deseada no es válida.

Pasos:

.  El ´Cliente´ ingresa al bot, envía el comando /start y  selecciona la opción menú
- Datos: Ninguno
- Resultado: El bot retorna un mensaje “A qué categoría desea ingresar”

. El cliente ingresa a alguna categoría.
- Datos: categoría
- Resultado: El bot retorna un mensaje “Lista de productos:”.

. El `cliente` Selecciona el producto que desea.
- Datos: producto
- Resultado: El bot retorna un mensaje “Cantidad que desea pedir:”.

. El `cliente` Manda una cantidad inválida.
- Datos: cantidad
- Resultado: El bot retorna un mensaje “La cantidad ingresada es inválida por favor vuelva a ingresar una cantidad”.

== 002 - Recepción de Pedidos

*Autor:* Ariel Monroy

*Fecha:* 8/3/2022

*Prioridad:* ALTA

=== Descripción

El `Cliente` debe seleccionar los platos que él desee junto con las cantidades de estos por medio del menú del bot, después debe añadir la ubicación para la entrega y finalmente enviar el `Pedido` En el restaurante el `Encargado` debe verificar si el restaurante puede cumplir con el `Pedido` para que este sea aceptado o rechazado. En caso de que el `Pedido` sea aceptado  el pedido un `Encargado` procederá a mandar un QR y se dará una hora estimada de llegada. Por otra parte si el `Pedido` fue rechazado el restaurante debe dar un comentario de los productos que no se puedan enviar.
Una vez que el `Cliente` realice el pago este debe mandar el comprobante al bot para que el `Pedido` sea preparado,el comprobante será verificado por el `Encargado`, en caso de que no se realice el pago antes de 10 minutos el bot cancelará automáticamente el `Pedido`.

El Pedido pasará por los siguientes estados:

* *ENVIADO:* Cuando el cliente envía su `Pedido` al BOT para ser revisado por el `Encargado`.
* *APROBADO*: Solicitud aprobada por el `Encargado` del Restaurante
* *RECHAZADO*: Solicitud rechazada por el `Encargado` del Restaurante
* *PAGADO*: El `Cliente` realiza el pago
* *CANCELADO*: El `Cliente` cancela una solicitud aprobada si no realiza el pago dentro del límite de tiempo, o si decide cancelarla antes de sea aprobada.

El diagrama de estados para  el `PEDIDO` será:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> ENVIADO
ENVIADO --> APROBADO
ENVIADO --> RECHAZADO
ENVIADO ---> CANCELADO
RECHAZADO ---> [*]
APROBADO --> PAGADO
APROBADO -> CANCELADO
PAGADO --> [*]
CANCELADO --> [*]
@enduml
....

==== Escenario
. El pedido se envía para ser revisado por el `Encargado`.
. El `Encargado` del restaurante aprueba y manda el QR
. El `Encargado` del restaurante rechaza el pedido
. El `Cliente` el pago del pedido
. El pedido se cancela por haber excedido el tiempo de pago
. El `Cliente` cancela el pedido antes de ser aprobado
. El `Cliente` cancela el pedido antes de realizar el pago

==== Casos de Prueba

*002.1.1* El pedido se envía para ser revisado por el `Encargado`.

Descripción: El pedido fue enviado y espera por la revisión del `Encargado`.

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

*002.1.2*  El `Encargado` del restaurante aprueba y manda el QR

Descripción: El pedido fue enviado y aprobado por el ´Encargado´

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, este contiene la hora   de estimada de llegada, el total del pedido incluyendo delivery y un QR para el pago .

*002.1.3* El `Encargado` del restaurante rechaza el pedido

Descripción: El pedido fue enviado y rechazado por el `Encargado`

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` rechaza el pedido
- Datos: Ninguno
- Resultado: El bot retorna un mensaje  "Los siguientes productos no están disponibles: ...."

*002.1.4*  El `Cliente` realiza el pago del pedido

Descripción: El pedido fue enviado y aprobado por el ´Encargado´, después este responde con un código QR para que se realice el pago del ´Pedido´.

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, el total del pedido incluyendo delivery y un QR para el pago.

. El `Cliente` realiza el pago mediante el código QR y envía el comprobante de la transferencia para su revisión.
- Datos: Comprobante de pago
- Resultado: El bot retorna un mensaje de confirmación, este contiene la hora   de     estimada de llegada.

*002.1.5* El pedido se cancela por haber excedido el tiempo de pago

Descripción: El pedido fue enviado, pero el `Cliente` decide cancelarlo

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, este contiene la hora   de estimada de llegada, el total del pedido incluyendo delivery y un QR para el pago .

. El ´Bot´ manda notificaciones cada 5 minutos durante 11 minutos.
- Datos: Ninguno
- Resultado: El bot retorna mensajes de “Le quedan … minutos para mandar el comprobante de pago”.

. El `Cliente` no manda el comprobante .
- Datos: Ninguno
- Resultado: El bot retorna un mensaje “El pedido fue cancelado”.

*002.1.6*  El `Cliente` cancela el pedido antes de ser aprobado

Descripción: El pedido fue enviado pero el `Cliente`  decide cancelarlo antes de que el `Encargado` lo apruebe.

Pasos:

.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Cliente` ingresa el comando para cancelar su pedido en curso
- Datos: Ninguno
- Resultado: El bot retorna un mensaje de confirmación de la cancelación.

*002.1.7* El `Cliente` cancela el pedido antes de realizar el pago

Descripción: El pedido fue enviado, pero el `Cliente` decide cancelarlo

Pasos:
.  El `Cliente` ingresa al bot, envía el comando /start y  selecciona los platos para el pedido
- Datos: Platos seleccionados
- Resultado: El bot retorna un mensaje pidiendo la dirección de entrega

. El `Cliente` Ingresa la dirección para enviar el pedido.
- Datos: Dirección de entrega
- Resultado: El bot retorna un mensaje de confirmación de la recepción.

. El `Encargado` aprueba el pedido
- Datos: Código QR
- Resultado: El bot retorna un mensaje de confirmación del pedido, este contiene la hora   de estimada de llegada, el total del pedido incluyendo delivery y un QR para el pago .

. El `Cliente` cancela el pedido.
- Datos: Ninguno
- Resultado: El bot retorna un mensaje “El pedido fue cancelado”.

== 003 - Modificar menu

*Autor:* Kevin Lecoña Marca

*Fecha:* 10/3/2022

*Prioridad:* ALTA

=== Descripcion

El `ENCARGADO` puede modificar el menu de restaurante que los `CLIENTES` podran ver para ordenar. Cuando ingrese a la opciones de Modificar Menu, el encargado podra visualizar todos los platos que tiene registrados en la base de datos y con un checkBox podra selecionar los platos que se vizualizar a los clientes.

La promoción pasará por los siguientes estados:

- Selecion: Cuando el `ENCARGADO` selecione los platos del menu
- actualizacion: Cuando se actualice el menu

Diagrama de estado para la selecion de platos:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

actor encargado
participant bot
database DB
actor clientes

encargado->bot: iniciar bot (/start)
bot->encargado: Menu de opciones(Lista de pedidos/promociones/cambiar el menu)
encargado->bot: cambiar menu
DB -> bot: Lista de platos
bot->encargado: Selecione el menu del dia
encargado->bot: Menu selecionado
bot -> encargado: Se publico el menu
bot -> clientes: Menu del dia
@enduml
....

== Escenarios

- Selecion de platos
- Validacion de informacion

== Casos de Prueba

*003.1.1 Selecion de platos*

Descripcion: El `ENCARGADO` seleciona los platos para el menu

Pasos:

1. Ingresar al Bot enviando el mensaje /start
data/ Selecionar una opcion
Resultado: Selecione una opcion
- Lista de pedidos
- Promociones
- Cambiar el menu
2. Ingresa a la opcion de Cambiar menu
- data /listado de platos del restaurante
- respuesta/ selecione los platos
3. El `ENCARGADO` seleciona los platos
- datos /platos selecionados
- resultado / publicar menu
4. El `ENCARGADO` confirma la publicacion
- datos /comfirmacion
- resultado /Menu publicado

*003.1.2 Validacion de datos*

Descripcion: valida que el menu no se publique sin ninguna informacion

Pasos:

1. Ingresar al Bot enviando el mensaje /start
data /Selecionar una opcion
Resultado: Selecione una opcion
- Lista de pedidos
- Promociones
- Cambiar el menu
2. Ingresa a la opcion de Cambiar menu
- data /listado de platos del restaurante
- respuesta/ selecione los platos
3. El `ENCARGADO` seleciona los platos
- datos /sin selecionar
- resultado / tiene que selecionar los platos
